### PR TITLE
assertEqual(a, round(b, x)) --> assertAlmostEqual(a, b, x)

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
With this PR I want to suggest to add a new error: `A503  prefer assertAlmostEqual()'s rounding instead of using round()`.

I very often found this pattern, even with `assertAlmostEqual`.

Please feel free to close this PR if you are not interested or change (or ask for changes) whatever you like.

### CODE REVIEW

**Comment by jparise** [comment]
I like this idea, but I'd prefer to keep the error codes a bit more generic. Maybe this could use A501?

**Comment by MarkusPiotrowski** [comment]
Dear Jon,
OK, I have put these issues into A501.

Personally, having worked a little bit on style issues using `flake8` for the Biopython project, I'd prefer to have more 'single issue' error codes, since this makes recognizing the issue easier and faster.  E.g., `pydocstyle` uses different error codes each for the similar error messages "Missing docstring in public module/public class/public method/public function. So you can easily list them separately to work on them.

**Comment by jparise** [comment]
I played with this a bit, and it's quite useful! I even found some occurrences of the anti-pattern in Pinterest's Python monorepo. 😉 

Locally, I simplified it to just:

```
--- a/flake8_assertive.py
+++ b/flake8_assertive.py
@@ -112,15 +112,11 @@ class Checker(object):
         elif any(arg for arg in node.args if is_constant(arg, False)):
             yield self.error(node, 'A502', 'assertFalse', obj=False)
         elif any(arg for arg in node.args if is_function_call(arg, 'round')):
-            yield self.error(node, 'A501',
-                             'built-in rounding of assertAlmostEqual',
-                             op='round')
+            yield self.error(node, 'A501', 'assertAlmostEqual', op='round()')

     def check_assertalmostequal(self, node):
         if any(arg for arg in node.args if is_function_call(arg, 'round')):
-            yield self.error(node, 'A501',
-                             'built-in rounding of assertAlmostEqual',
-                             op='round')
+            yield self.error(node, 'A501', 'assertAlmostEqual', op='round()')

     def check_assertnotequal(self, node):
         if any(arg for arg in node.args if is_constant(arg, None)):
```

... which is closer to the existing error messages. I'm not sure if that loses some of the clarity from the original, more verbose message. That's perhaps an argument in favor of giving this its own error code, as you originally proposed.

Sorry for the back-and-forth as I try to decide the best way to incorporate this new check. It's _slightly_ different than the others and doesn't quite fit the existing patterns.

**Comment by MarkusPiotrowski** [comment]
The reason why I explicitely mention the built-in rounding in the error message is that `round()` and `assertAlmostEqual` default to different precisions, thus one cannot simply replace `assertEqual(1, round(1.47)` with `assertAlmostEqual(1, 1.47)`. With the hint to 'built-in rounding' people may recognize that they can change/define the rounding precision for `assertAlmostEqual` (I didn't know that before).

Also, if the issue arises from an `assertAlmostEqual`, the message to "prefer assertAlmostEqual() for round() expressions" is, mh, strange, without saying what they should do differently.

**Comment by jparise** [comment]
@MarkusPiotrowski I have a good understanding of your reasoning now. Before I merge this, would you like to go back to the dedicated error code that you originally proposed, or shall we leave it as A501? I'm supporting of both approaches and want to give you the choice as the author/contributor.

If you prefer the A503 approach, please adjust your original code to pass `func` to the `error()` method so that the built-in snakecasing functionality can apply its transformation when that feature is enabled.

**Comment by MarkusPiotrowski** [comment]
@jparise I think we can leave it with the error code A501.
Thank you!

**Comment by jparise** [comment]
Thanks very much, @MarkusPiotrowski!

**Comment by peterjc** [comment]
Just found this via running flake8-assertive on Biopython (Hi Markus!), and personally would have voted for the separate error code for the reasons suggested. In general I think flake8-assertive would benefit from more separate codes, particularly for aiding gradual cleanup of large code bases.

**Comment by jparise** [comment]
@peterjc I can see both sides of the "more error codes" decision. At the moment, I'm inclined to keep things as they are (fewer codes) given that's how this linter has worked thus far, but I'm not opposed to making a change as part of a major version bump.

**Pull request merged**
